from beamngpy import BeamNGpy,Scenario,Vehicle, setup_logging
from beamngpy.sensors import Camera, GForces, Lidar, Electrics, Damage
setup_logging()
bng = BeamNGpy('localhost', 64270)
scenario = Scenario('Mytest', 'demo')
vehicle = Vehicle('ego_vehicle', model='etk800',licence='RED', color='Green')
pos = (-0.3, 1, 1.0)
direction = (0, 1, 0)
fov = 120
resolution = (512, 512)
front_camera = Camera(pos, direction, fov, resolution,
                      colour=True, depth=True, annotation=True)
pos = (0.0, 3, 1.0)
direction = (0, -1, 0)
fov = 90
resolution = (512, 512)
back_camera = Camera(pos, direction, fov, resolution,
                     colour=True, depth=True, annotation=True)
gforces = GForces()
electrics = Electrics()
damage = Damage()
lidar = Lidar()
vehicle.attach_sensor('front_cam', front_camera)
vehicle.attach_sensor('back_cam', back_camera)
vehicle.attach_sensor('gforces', gforces)
vehicle.attach_sensor('lidar', lidar)
vehicle.attach_sensor('electrics', electrics)
vehicle.attach_sensor('damage', damage)
scenario.add_vehicle(vehicle, pos=(104.647,-1.92827,-3.54338),rot=(0,0,90))
vehicle1 = Vehicle('test_vehicle', model='etk800',licence='RED', color='Blue')
scenario.add_vehicle(vehicle1,pos=(-9.66595, -90.7465,-3.45737),rot=(0,0,180))
scenario.make(bng)
bng.open()
bng.load_scenario(scenario)
vehicle.ai_set_mode('Manual')
vehicle.ai_set_waypoint('DecalRoad5248_4')
#vehicle1.ai_set_mode('Manual')
#vehicle1.ai_set_waypoint('DecalRoad5250_4')
vehicle1.control(throttle=0.44)
